/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { ButtonSize, ButtonType, ButtonVariant } from "./components/button/lm-prototype-stencil-button";
import { IconName } from "@lm-prototype-stencil/icons";
import { DropdownSize, DropdownVariant, IconName as IconName1 } from "./components/dropdown/lm-prototype-stencil-dropdown";
import { IconName as IconName2 } from "./components/dropdown/lm-prototype-stencil-dropdown-item";
export { ButtonSize, ButtonType, ButtonVariant } from "./components/button/lm-prototype-stencil-button";
export { IconName } from "@lm-prototype-stencil/icons";
export { DropdownSize, DropdownVariant, IconName as IconName1 } from "./components/dropdown/lm-prototype-stencil-dropdown";
export { IconName as IconName2 } from "./components/dropdown/lm-prototype-stencil-dropdown-item";
export namespace Components {
    interface LmPrototypeStencilButton {
        /**
          * @default false
         */
        "disabled": boolean;
        "icon"?: IconName;
        "iconEnd"?: IconName;
        /**
          * @default false
         */
        "loading": boolean;
        "name"?: string;
        /**
          * @default 'md'
         */
        "size": ButtonSize;
        /**
          * @default 'button'
         */
        "type": ButtonType;
        "value"?: string;
        /**
          * @default 'primary'
         */
        "variant": ButtonVariant;
    }
    interface LmPrototypeStencilDropdown {
        /**
          * @default false
         */
        "disabled": boolean;
        "icon"?: IconName1;
        "iconEnd"?: IconName1;
        "label"?: string;
        "name"?: string;
        /**
          * @default false
         */
        "open": boolean;
        /**
          * @default 'Välj alternativ...'
         */
        "placeholder": string;
        /**
          * @default false
         */
        "required": boolean;
        /**
          * @default 'md'
         */
        "size": DropdownSize;
        /**
          * @default ''
         */
        "value": string;
        /**
          * @default 'secondary'
         */
        "variant": DropdownVariant;
    }
    interface LmPrototypeStencilDropdownItem {
        "icon"?: IconName2;
        "iconEnd"?: IconName2;
        /**
          * @default ''
         */
        "value": string;
    }
}
export interface LmPrototypeStencilDropdownCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLLmPrototypeStencilDropdownElement;
}
export interface LmPrototypeStencilDropdownItemCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLLmPrototypeStencilDropdownItemElement;
}
declare global {
    interface HTMLLmPrototypeStencilButtonElement extends Components.LmPrototypeStencilButton, HTMLStencilElement {
    }
    var HTMLLmPrototypeStencilButtonElement: {
        prototype: HTMLLmPrototypeStencilButtonElement;
        new (): HTMLLmPrototypeStencilButtonElement;
    };
    interface HTMLLmPrototypeStencilDropdownElementEventMap {
        "lmChange": { value: string; label: string };
    }
    interface HTMLLmPrototypeStencilDropdownElement extends Components.LmPrototypeStencilDropdown, HTMLStencilElement {
        addEventListener<K extends keyof HTMLLmPrototypeStencilDropdownElementEventMap>(type: K, listener: (this: HTMLLmPrototypeStencilDropdownElement, ev: LmPrototypeStencilDropdownCustomEvent<HTMLLmPrototypeStencilDropdownElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLLmPrototypeStencilDropdownElementEventMap>(type: K, listener: (this: HTMLLmPrototypeStencilDropdownElement, ev: LmPrototypeStencilDropdownCustomEvent<HTMLLmPrototypeStencilDropdownElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLLmPrototypeStencilDropdownElement: {
        prototype: HTMLLmPrototypeStencilDropdownElement;
        new (): HTMLLmPrototypeStencilDropdownElement;
    };
    interface HTMLLmPrototypeStencilDropdownItemElementEventMap {
        "lm-dropdown-item-select": void;
    }
    interface HTMLLmPrototypeStencilDropdownItemElement extends Components.LmPrototypeStencilDropdownItem, HTMLStencilElement {
        addEventListener<K extends keyof HTMLLmPrototypeStencilDropdownItemElementEventMap>(type: K, listener: (this: HTMLLmPrototypeStencilDropdownItemElement, ev: LmPrototypeStencilDropdownItemCustomEvent<HTMLLmPrototypeStencilDropdownItemElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLLmPrototypeStencilDropdownItemElementEventMap>(type: K, listener: (this: HTMLLmPrototypeStencilDropdownItemElement, ev: LmPrototypeStencilDropdownItemCustomEvent<HTMLLmPrototypeStencilDropdownItemElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLLmPrototypeStencilDropdownItemElement: {
        prototype: HTMLLmPrototypeStencilDropdownItemElement;
        new (): HTMLLmPrototypeStencilDropdownItemElement;
    };
    interface HTMLElementTagNameMap {
        "lm-prototype-stencil-button": HTMLLmPrototypeStencilButtonElement;
        "lm-prototype-stencil-dropdown": HTMLLmPrototypeStencilDropdownElement;
        "lm-prototype-stencil-dropdown-item": HTMLLmPrototypeStencilDropdownItemElement;
    }
}
declare namespace LocalJSX {
    interface LmPrototypeStencilButton {
        /**
          * @default false
         */
        "disabled"?: boolean;
        /**
          * The `id` of a `<form>` element to associate this element with.
         */
        "form"?: string;
        "icon"?: IconName;
        "iconEnd"?: IconName;
        /**
          * @default false
         */
        "loading"?: boolean;
        "name"?: string;
        /**
          * @default 'md'
         */
        "size"?: ButtonSize;
        /**
          * @default 'button'
         */
        "type"?: ButtonType;
        "value"?: string;
        /**
          * @default 'primary'
         */
        "variant"?: ButtonVariant;
    }
    interface LmPrototypeStencilDropdown {
        /**
          * @default false
         */
        "disabled"?: boolean;
        /**
          * The `id` of a `<form>` element to associate this element with.
         */
        "form"?: string;
        "icon"?: IconName1;
        "iconEnd"?: IconName1;
        "label"?: string;
        "name"?: string;
        "onLmChange"?: (event: LmPrototypeStencilDropdownCustomEvent<{ value: string; label: string }>) => void;
        /**
          * @default false
         */
        "open"?: boolean;
        /**
          * @default 'Välj alternativ...'
         */
        "placeholder"?: string;
        /**
          * @default false
         */
        "required"?: boolean;
        /**
          * @default 'md'
         */
        "size"?: DropdownSize;
        /**
          * @default ''
         */
        "value"?: string;
        /**
          * @default 'secondary'
         */
        "variant"?: DropdownVariant;
    }
    interface LmPrototypeStencilDropdownItem {
        "icon"?: IconName2;
        "iconEnd"?: IconName2;
        "onLm-dropdown-item-select"?: (event: LmPrototypeStencilDropdownItemCustomEvent<void>) => void;
        /**
          * @default ''
         */
        "value"?: string;
    }

    interface LmPrototypeStencilButtonAttributes {
        "variant": ButtonVariant;
        "size": ButtonSize;
        "type": ButtonType;
        "name": string;
        "value": string;
        "icon": IconName;
        "iconEnd": IconName;
        "disabled": boolean;
        "loading": boolean;
    }
    interface LmPrototypeStencilDropdownAttributes {
        "open": boolean;
        "variant": DropdownVariant;
        "size": DropdownSize;
        "disabled": boolean;
        "required": boolean;
        "value": string;
        "label": string;
        "placeholder": string;
        "name": string;
        "icon": IconName;
        "iconEnd": IconName;
    }
    interface LmPrototypeStencilDropdownItemAttributes {
        "value": string;
        "icon": IconName;
        "iconEnd": IconName;
    }

    interface IntrinsicElements {
        "lm-prototype-stencil-button": Omit<LmPrototypeStencilButton, keyof LmPrototypeStencilButtonAttributes> & { [K in keyof LmPrototypeStencilButton & keyof LmPrototypeStencilButtonAttributes]?: LmPrototypeStencilButton[K] } & { [K in keyof LmPrototypeStencilButton & keyof LmPrototypeStencilButtonAttributes as `attr:${K}`]?: LmPrototypeStencilButtonAttributes[K] } & { [K in keyof LmPrototypeStencilButton & keyof LmPrototypeStencilButtonAttributes as `prop:${K}`]?: LmPrototypeStencilButton[K] };
        "lm-prototype-stencil-dropdown": Omit<LmPrototypeStencilDropdown, keyof LmPrototypeStencilDropdownAttributes> & { [K in keyof LmPrototypeStencilDropdown & keyof LmPrototypeStencilDropdownAttributes]?: LmPrototypeStencilDropdown[K] } & { [K in keyof LmPrototypeStencilDropdown & keyof LmPrototypeStencilDropdownAttributes as `attr:${K}`]?: LmPrototypeStencilDropdownAttributes[K] } & { [K in keyof LmPrototypeStencilDropdown & keyof LmPrototypeStencilDropdownAttributes as `prop:${K}`]?: LmPrototypeStencilDropdown[K] };
        "lm-prototype-stencil-dropdown-item": Omit<LmPrototypeStencilDropdownItem, keyof LmPrototypeStencilDropdownItemAttributes> & { [K in keyof LmPrototypeStencilDropdownItem & keyof LmPrototypeStencilDropdownItemAttributes]?: LmPrototypeStencilDropdownItem[K] } & { [K in keyof LmPrototypeStencilDropdownItem & keyof LmPrototypeStencilDropdownItemAttributes as `attr:${K}`]?: LmPrototypeStencilDropdownItemAttributes[K] } & { [K in keyof LmPrototypeStencilDropdownItem & keyof LmPrototypeStencilDropdownItemAttributes as `prop:${K}`]?: LmPrototypeStencilDropdownItem[K] };
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "lm-prototype-stencil-button": LocalJSX.IntrinsicElements["lm-prototype-stencil-button"] & JSXBase.HTMLAttributes<HTMLLmPrototypeStencilButtonElement>;
            "lm-prototype-stencil-dropdown": LocalJSX.IntrinsicElements["lm-prototype-stencil-dropdown"] & JSXBase.HTMLAttributes<HTMLLmPrototypeStencilDropdownElement>;
            "lm-prototype-stencil-dropdown-item": LocalJSX.IntrinsicElements["lm-prototype-stencil-dropdown-item"] & JSXBase.HTMLAttributes<HTMLLmPrototypeStencilDropdownItemElement>;
        }
    }
}
