/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { IconName } from "./registry";
export { IconName } from "./registry";
export namespace Components {
    interface LmPrototypeStencilIcon {
        "label"?: string;
        /**
          * @default ''
         */
        "name": IconName | '';
    }
}
declare global {
    interface HTMLLmPrototypeStencilIconElement extends Components.LmPrototypeStencilIcon, HTMLStencilElement {
    }
    var HTMLLmPrototypeStencilIconElement: {
        prototype: HTMLLmPrototypeStencilIconElement;
        new (): HTMLLmPrototypeStencilIconElement;
    };
    interface HTMLElementTagNameMap {
        "lm-prototype-stencil-icon": HTMLLmPrototypeStencilIconElement;
    }
}
declare namespace LocalJSX {
    interface LmPrototypeStencilIcon {
        "label"?: string;
        /**
          * @default ''
         */
        "name"?: IconName | '';
    }

    interface LmPrototypeStencilIconAttributes {
        "name": IconName | '';
        "label": string;
    }

    interface IntrinsicElements {
        "lm-prototype-stencil-icon": Omit<LmPrototypeStencilIcon, keyof LmPrototypeStencilIconAttributes> & { [K in keyof LmPrototypeStencilIcon & keyof LmPrototypeStencilIconAttributes]?: LmPrototypeStencilIcon[K] } & { [K in keyof LmPrototypeStencilIcon & keyof LmPrototypeStencilIconAttributes as `attr:${K}`]?: LmPrototypeStencilIconAttributes[K] } & { [K in keyof LmPrototypeStencilIcon & keyof LmPrototypeStencilIconAttributes as `prop:${K}`]?: LmPrototypeStencilIcon[K] };
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "lm-prototype-stencil-icon": LocalJSX.IntrinsicElements["lm-prototype-stencil-icon"] & JSXBase.HTMLAttributes<HTMLLmPrototypeStencilIconElement>;
        }
    }
}
