'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

import type { JSX } from "@lm-prototype-stencil/icons/dist/components";
import { LmPrototypeStencilIcon as LmPrototypeStencilIconElement, defineCustomElement as defineLmPrototypeStencilIcon } from "@lm-prototype-stencil/icons/dist/components/lm-prototype-stencil-icon.js";

export type LmPrototypeStencilIconEvents = NonNullable<unknown>;

export const LmPrototypeStencilIcon: StencilReactComponent<LmPrototypeStencilIconElement, LmPrototypeStencilIconEvents, JSX.LmPrototypeStencilIcon> = /*@__PURE__*/ createComponent<LmPrototypeStencilIconElement, LmPrototypeStencilIconEvents, JSX.LmPrototypeStencilIcon>({
    tagName: 'lm-prototype-stencil-icon',
    elementClass: LmPrototypeStencilIconElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as LmPrototypeStencilIconEvents,
    defineCustomElement: defineLmPrototypeStencilIcon
});
